### ISSUE TITLE
main.py doesn't work

### ISSUE THREAD

**Issue by dortamiguel** [jackromo/gestures#1]
When I try to do **python main.py** I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    main()
  File "main.py", line 18, in main
    contours = getContours(mask)
  File "/Users/miguel/src/kinect/lib/kinect-gestures/gestures/depthmap.py", line 24, in getContours
    image, contours, hierarchy = cv2.findContours(threshImg, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack
```

I'm running mac os x yosemite the latest version.

**Comment by jackromo** [comment]
Hello,

I'm using OpenCV 2.4. You might be using a different version (3.0?), where the findContours method only returns a 2-tuple of the contours and hierarchy instead of a 3-tuple of the image, contours and hierarchy.

You essentially have two options here. You can uninstall OpenCV and install OpenCV 2.4.11 or 2.4.10 (not ideal but works), or you can change line 24 in depthmap.py to be:

contours, hierarchy = cv2.findContours(threshImg, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

Try that last option first, and see if it works. If not, I'd like to see the error message it gives.

I think I accidentally wrote that this requires OpenCV 3.0; sorry about that. It should be 2.4.

(EDIT: None of this is true - I'm using OpenCV 3.0.0, as I discovered by checking again a few days after writing this comment.)

**Comment by dortamiguel** [comment]
When I change that line I get this:

```
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /tmp/opencv20150810-26088-1150u2z/opencv-2.4.12/modules/highgui/src/window.cpp, line 261
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    main()
  File "main.py", line 29, in main
    cv2.imshow('image', img)
cv2.error: /tmp/opencv20150810-26088-1150u2z/opencv-2.4.12/modules/highgui/src/window.cpp:261: error: (-215) size.width>0 && size.height>0 in function imshow
```

I'm using opencv 2.4.12 from brew in mac.

**Comment by jackromo** [comment]
It's evident that it's trying to display an image with a height and width of 0, ie. a nonexistent image.

Would you mind showing what is displayed when you replace line 12 in the depthmap.py file with the following lines:

final_img = depth.astype(np.uint8)
print final_img.shape
return final_img

This will print a series of results stating the dimensions in pixels of the image being analyzed from the Kinect. If this states (0,0) or another result at any point, the issue would be in the getDepthMap() function or with the Kinect - if it states (480, 640) or something else, then further investigation would be required.

What version of Python are you using, out of interest? Do you have OpenKinect (also called libfreenect) for Python installed? Does the following example work on your computer -> http://euanfreeman.co.uk/openkinect-python-and-opencv/ <- ? If it doesn't, there's an issue with your implementation of OpenKinect.

**Comment by dortamiguel** [comment]
When I replace the lines I get this:

```
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /tmp/opencv20150810-26088-1150u2z/opencv-2.4.12/modules/highgui/src/window.cpp, line 261
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    main()
  File "main.py", line 29, in main
    cv2.imshow('image', img)
cv2.error: /tmp/opencv20150810-26088-1150u2z/opencv-2.4.12/modules/highgui/src/window.cpp:261: error: (-215) size.width>0 && size.height>0 in function imshow
```

I have libfreenect installed, and the example from the website it runs but doesn't output anything.
I'm using python 2.7.10.
Also my kinect seems to work fine with other apps like this one https://github.com/mwcz/Kimotion 

Maybe the problem is because of my opencv installation? I installed it through brew.

**Comment by jackromo** [comment]
Hey,

After looking again, it appears that I'm not using version 2.4 - I've just looked, and I am in fact using 3.0.0, as I wrote in the README file. Your version of OpenCV is therefore a problem - OpenCV 3.0.0 and 2.4.x have compatibility issues, much like Python 2 and Python 3. Therefore, you should update to version 3.0.0 of OpenCV, and can then undo all the changes I've previously advised, as they will all be made irrelevant by updating.

Sorry about that, and hope this helps!

**Comment by dortamiguel** [comment]
Awesome! It was that!

Now is working, good job!

**Comment by MuhaiminMN** [comment]
sir ellipticaldoor , can you help me.. i also got this error.. how you solve this problem? thank you.,. :)
my opencv version is  3.0 & python 2.7.6..

**Comment by MuhaiminMN** [comment]
This is error when run python main.py @ellipticaldoor @jackromo 

muhaimin@FYP:~/gestures-master$ python main.py
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    main()
  File "main.py", line 18, in main
    contours = getContours(mask)
  File "/home/muhaimin/gestures-master/depthmap.py", line 24, in getContours
    image, contours, hierarchy = cv2.findContours(threshImg, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack
muhaimin@FYP:~/gestures-master$
